# # syntax=docker/dockerfile:1.7

# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN --mount=type=cache,target=/root/.npm \
#     npm ci --no-audit --no-fund --prefer-offline

# COPY . .

# EXPOSE 5000

# CMD ["npm", "run", "dev"]


# syntax=docker/dockerfile:1.7

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Temporary workaround for corporate SSL inspection
RUN npm config set strict-ssl false \
    && (npm ci --no-audit --no-fund --prefer-offline || npm install --no-audit --no-fund)

COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]